name = "Leentech Neo"
author = "Tim & Leen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfc6b100ff941c07957ff373e7829e734d832ce56ecd42b5e4ee621799ccc92d"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
