name = "Leentech Neo"
author = "Tim & Leen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4894f11ebb8ce317988b5e46f48579b17292fa135388796e6f67d49b5f4fa2b8"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
