name = "Leentech Neo"
author = "Tim & Leen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f798d47cb3efaacdb6271e420b9ffbd5ae234f401c574e803f9b6b59921402a"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
