ClientEvents.lang("en_us", event => {
    event.renameBiome("minecraft:dark_forest", "Dark Oak Forest")
    event.renameBiome("atmospheric:rainforest", "Monkey Grove")
    event.renameBiome("atmospheric:rainforest_basin", "Flooded Forest")
    event.renameBiome("atmospheric:sparse_rainforest", "Sparse Monkey Grove")
    event.renameBiome("atmospheric:sparse_rainforest_basin", "Sparse Flooded Forest")
    event.renameBiome("environmental:marsh", "Morass")
    event.renameBiome("environmental:pine_barrens", "Young Pine Barrens")
    event.renameBiome("environmental:pine_slopes", "Young Pine Slopes")
    event.renameBiome("environmental:snowy_pine_barrens", "Snowy Young Pine Barrens")
    event.renameBiome("regions_unexplored:bamboo_forest", "Bamboo Thicket")
    event.renameBiome("regions_unexplored:redwoods", "Redwood Forest")
    event.renameBiome("deep_aether:golden_grove", "Sunroot Grove")
    event.renameBiome("deep_aether:golden_heights", "Gilded Heights")
    event.renameBiome("darwiniv:pocketforest", "Alien Forest")
    event.renameBiome("darwiniv:prairie", "Alien Prairie")
    event.renameBiome("darwiniv:salt_shore", "Amoebic Shore")
    event.renameBiome("darwiniv:litoralzone", "Saline Valley")
})