ClientEvents.lang("en_us", event => {
    event.renameBiome("minecraft:dark_forest", "Dark Oak Forest")
    event.renameBiome("atmospheric:rainforest", "Monkey Woods")
    event.renameBiome("atmospheric:rainforest_basin", "Jungle Delta")
    event.renameBiome("atmospheric:sparse_rainforest", "Sparse Monkey Woods")
    event.renameBiome("atmospheric:sparse_rainforest_basin", "Sunken Forest")
    event.renameBiome("environmental:marsh", "Morass")
    event.renameBiome("environmental:pine_barrens", "Young Pine Barrens")
    event.renameBiome("environmental:pine_slopes", "Young Pine Slopes")
    event.renameBiome("environmental:snowy_pine_barrens", "Snowy Young Pine Barrens")
    event.renameBiome("regions_unexplored:bamboo_forest", "Bamboo Grove")
    event.renameBiome("regions_unexplored:redwoods", "Redwood Forest")
    event.renameBiome("deep_aether:golden_grove", "Sunroot Grove")
    event.renameBiome("deep_aether:golden_heights", "Sunroot Hill")
})