# Don't change this! Version used to track needed updates.
version = 0
# Adjusts hamster spawn frequency. Higher = more chaos. 1 = blissful silence.
spawnWeight = 20
# Maximum hamsters per spawn group. Because sometimes one just isn't cute enough.
maxGroupSize = 1
# A list of biome tags where hamsters can spawn. Format: 'mod_id:tag_name'. For example, 'minecraft:is_forest'.
spawnBiomeTags = []
# A list of convention biome tags where hamsters can spawn. Used for broad mod compatibility.
spawnBiomeConventionTags = []
# A list of specific biome IDs to ALWAYS allow spawns in, even if they don't match the tags above. Format: 'mod_id:biome_name'. For example, 'minecraft:plains'.
includeBiomes = [
    "minecraft:sunflower_plains",
    "biomesoplenty:grassland",
    "biomesoplenty:pasture"
]
# A list of specific biome IDs to NEVER allow spawns in, even if they match a tag. This overrides all other settings. Format: 'mod_id:biome_name'. For example, 'minecraft:plains'.
excludeBiomes = []
# A list of Biome Tags to NEVER allow spawns in. For excluding broad categories like Oceans or Rivers without listing every single ID. Overrides inclusions.
excludeBiomeTags = []
# A list of mathematical 3D color groups permitted to spawn as overlays on wild hamsters. By default, it's set to natural boring color groups like WHITE, LIGHT_GRAY, DARK_GRAY, and CREAM so your world doesn't look like a clown exploded. Available zones: WHITE, BLUE, SKY, LAVENDER, ROSE, LIGHT_GRAY, DARK_GRAY, CREAM, BLACK, CHOCOLATE, ORANGE.
allowedWildOverlayZones = [
    "WHITE",
    "LIGHT_GRAY",
    "DARK_GRAY",
    "CREAM"
]
# If true, wild overlays must be strictly brighter than the base coat. True by default to prevent Black overlays on Cream hamsters.
enforceBrighterOverlays = true
# If true, wild overlays must be less saturated than the base coat. On by default to prevent Cream overlays on Black and Gray hamsters.
enforceMoreMutedOverlays = true
# Hamsters in these base coat color groups will refuse to spawn with wild overlays from the 'Clashing Overlay Colors' list.
restrictedBaseZones = [
    "BLUE",
    "LAVENDER"
]
# A list of wild overlays that look unnatural when combined with the 'Clashing Base Colors'. By default, this prevents Cream and Dark Gray wild overlays on Blue and Lavender hamsters.
clashingOverlayZones = [
    "CREAM",
    "DARK_GRAY"
]
icyBiomes = [
    "terralith:glacial_chasm",
    "terralith:mirage_isles",
    "terralith:moonlight_valley",
    "biomesoplenty:enchanted_garden"
]
icyTags = [
    "adorablehamsterpets:is_icy"
]
icyExclusionBiomes = [  ]
icyExclusionTags = [  ]
# Format 'VARIANT_TYPE:WEIGHT'. The total weight must equal 100, so I hope you graduated third grade. Available groupings of hamster types: WHITE, BLUE, SKY, LAVENDER, ROSE, LIGHT_GRAY, DARK_GRAY, CREAM, BLACK, CHOCOLATE, ORANGE. Join The Cheek Pouch Discord server to suggest new groupings if you designed a custom hamster texture that you think belongs in its own unique grouping (i.e. maybe a 'mossy' green hamster?).
icyWeights = [
    "BLUE:25",
    "SKY:25",
    "WHITE:50"
]
magicalBiomes = [
    "minecraft:cherry_grove",
    "terralith:sakura_valley",
    "biomesoplenty:fungi_forest",
    "biomesoplenty:mystic_grove"
]
magicalTags = [
    "adorablehamsterpets:is_magical",
    "adorablehamsterpets:is_mushroom",
    "terralith:mystical"
]
magicalExclusionBiomes = [  ]
magicalExclusionTags = [  ]
# Format 'VARIANT_TYPE:WEIGHT'. The total weight must equal 100, so I hope you graduated third grade. Available groupings of hamster types: WHITE, BLUE, SKY, LAVENDER, ROSE, LIGHT_GRAY, DARK_GRAY, CREAM, BLACK, CHOCOLATE, ORANGE. Join The Cheek Pouch Discord server to suggest new groupings if you designed a custom hamster texture that you think belongs in its own unique grouping (i.e. maybe a 'mossy' green hamster?).
magicalWeights = [
    "LAVENDER:70",
    "ROSE:30"
]
snowyBiomes = [
    "terralith:snowy_maple_forest",
    "terralith:wintry_forest",
    "terralith:alpine_grove",
    "terralith:siberian_grove"
]
snowyTags = [
    "adorablehamsterpets:is_cold",
    "adorablehamsterpets:is_snowy"
]
snowyExclusionBiomes = [
    "minecraft:deep_frozen_ocean",
    "minecraft:frozen_ocean",
    "minecraft:stony_shore",
    "minecraft:windswept_forest",
    "minecraft:windswept_gravelly_hills",
    "minecraft:windswept_hills",
    "minecraft:taiga",
    "minecraft:old_growth_pine_taiga",
    "minecraft:old_growth_spruce_taiga"
]
snowyExclusionTags = [  ]
# Format 'VARIANT_TYPE:WEIGHT'. The total weight must equal 100, so I hope you graduated third grade. Available groupings of hamster types: WHITE, BLUE, SKY, LAVENDER, ROSE, LIGHT_GRAY, DARK_GRAY, CREAM, BLACK, CHOCOLATE, ORANGE. Join The Cheek Pouch Discord server to suggest new groupings if you designed a custom hamster texture that you think belongs in its own unique grouping (i.e. maybe a 'mossy' green hamster?).
snowyWeights = [
    "WHITE:100"
]
rockyBiomes = [
    "minecraft:stony_shore",
    "terralith:stony_spires"
]
rockyTags = [
    "adorablehamsterpets:is_mountain",
    "adorablehamsterpets:is_sparse_vegetation",
    "terralith:cliffs"
]
rockyExclusionBiomes = [  ]
rockyExclusionTags = [
    "minecraft:is_badlands",
    "minecraft:is_jungle",
    "minecraft:is_savanna",
    "minecraft:is_beach",
    "adorablehamsterpets:is_sandy"
]
# Format 'VARIANT_TYPE:WEIGHT'. The total weight must equal 100, so I hope you graduated third grade. Available groupings of hamster types: WHITE, BLUE, SKY, LAVENDER, ROSE, LIGHT_GRAY, DARK_GRAY, CREAM, BLACK, CHOCOLATE, ORANGE. Join The Cheek Pouch Discord server to suggest new groupings if you designed a custom hamster texture that you think belongs in its own unique grouping (i.e. maybe a 'mossy' green hamster?).
mountainWeights = [
    "LIGHT_GRAY:50",
    "DARK_GRAY:50"
]
darkBiomes = [
    "minecraft:deep_dark"
]
darkTags = [
    "adorablehamsterpets:is_wet",
    "adorablehamsterpets:is_cave"
]
darkExclusionBiomes = [  ]
darkExclusionTags = [
    "minecraft:is_jungle",
    "minecraft:is_beach"
]
# Format 'VARIANT_TYPE:WEIGHT'. The total weight must equal 100, so I hope you graduated third grade. Available groupings of hamster types: WHITE, BLUE, SKY, LAVENDER, ROSE, LIGHT_GRAY, DARK_GRAY, CREAM, BLACK, CHOCOLATE, ORANGE. Join The Cheek Pouch Discord server to suggest new groupings if you designed a custom hamster texture that you think belongs in its own unique grouping (i.e. maybe a 'mossy' green hamster?).
darkWeights = [
    "BLACK:80",
    "DARK_GRAY:20"
]
sandyBiomes = [
    "minecraft:old_growth_birch_forest",
    "minecraft:birch_forest",
    "terralith:ancient_sands",
    "terralith:sandstone_valley",
    "biomesoplenty:wasteland"
]
sandyTags = [
    "adorablehamsterpets:is_sandy"
]
sandyExclusionBiomes = [
    "terralith:gravel_beach"
]
sandyExclusionTags = [
    "minecraft:is_badlands"
]
# Format 'VARIANT_TYPE:WEIGHT'. The total weight must equal 100, so I hope you graduated third grade. Available groupings of hamster types: WHITE, BLUE, SKY, LAVENDER, ROSE, LIGHT_GRAY, DARK_GRAY, CREAM, BLACK, CHOCOLATE, ORANGE. Join The Cheek Pouch Discord server to suggest new groupings if you designed a custom hamster texture that you think belongs in its own unique grouping (i.e. maybe a 'mossy' green hamster?).
sandyWeights = [
    "CREAM:100"
]
forestBiomes = [
    "terralith:cloud_forest",
    "biomesoplenty:redwood_forest"
]
forestTags = [
    "adorablehamsterpets:is_forest",
    "adorablehamsterpets:is_dense_vegetation"
]
forestExclusionBiomes = [  ]
forestExclusionTags = [
    "adorablehamsterpets:is_plains"
]
# Format 'VARIANT_TYPE:WEIGHT'. The total weight must equal 100, so I hope you graduated third grade. Available groupings of hamster types: WHITE, BLUE, SKY, LAVENDER, ROSE, LIGHT_GRAY, DARK_GRAY, CREAM, BLACK, CHOCOLATE, ORANGE. Join The Cheek Pouch Discord server to suggest new groupings if you designed a custom hamster texture that you think belongs in its own unique grouping (i.e. maybe a 'mossy' green hamster?).
forestWeights = [
    "CHOCOLATE:100"
]
# Format 'VARIANT_TYPE:WEIGHT'. The total weight must equal 100, so I hope you graduated third grade. Available groupings of hamster types: WHITE, BLUE, SKY, LAVENDER, ROSE, LIGHT_GRAY, DARK_GRAY, CREAM, BLACK, CHOCOLATE, ORANGE. Join The Cheek Pouch Discord server to suggest new groupings if you designed a custom hamster texture that you think belongs in its own unique grouping (i.e. maybe a 'mossy' green hamster?).
plainsWeights = [
    "ORANGE:100"
]
# The overall probability (0.0 to 1.0) that ANY wild hamster has stuffed something in its face. Set to 0.0 to enforce strict economic austerity.
globalCheekLootChance = 0.5
# The curated selection of pocket lint, seeds, and snacks that hamsters naturally forage. Edit this if you think hamsters should naturally forage for diamonds.
defaultCheekLootList = [
    "minecraft:wheat_seeds",
    "minecraft:pumpkin_seeds",
    "minecraft:melon_seeds",
    "minecraft:beetroot_seeds",
    "minecraft:carrot",
    "minecraft:potato",
    "minecraft:poisonous_potato",
    "minecraft:apple",
    "minecraft:feather",
    "minecraft:string",
    "minecraft:gold_nugget",
    "minecraft:iron_nugget",
    "minecraft:flint",
    "adorablehamsterpets:sunflower_seeds",
    "adorablehamsterpets:cucumber_seeds",
    "adorablehamsterpets:green_bean_seeds",
    "adorablehamsterpets:acorn"
]
# The chance (0.0 to 1.0) that a wild hamster spawns with the default junk (seeds, nuggets, carrots, etc). 0.5 = 50%.
defaultCheekLootChance = 0.5
# A list of item IDs (e.g. 'minecraft:cookie') or tags (e.g. '#c:fruits') that wild hamsters can spawn with. If you want them to spawn with Nether Stars, this is where you make that bad decision.
extraCheekLootList = [  ]
# The chance (0.0 to 1.0) that a wild hamster spawns with items from your Extra Loot list above. Independent of the default loot check.
extraCheekLootChance = 0.5
# The shiny rocks, glowing berries, and industrial debris found in the cheeks of cave-dwelling hamsters. Spelunking rodents have expensive tastes.
caveCheekLootList = [
    "minecraft:raw_iron",
    "minecraft:raw_copper",
    "minecraft:raw_gold",
    "minecraft:coal",
    "minecraft:amethyst_shard",
    "minecraft:glow_berries",
    "minecraft:redstone",
    "minecraft:lapis_lazuli",
    "minecraft:flint",
    "minecraft:clay_ball"
]
# The chance (0.0 to 1.0) that a hamster spawning in a cave actually found something cool instead of just a rock. Applies ONLY to hamsters spawning in valid cave biomes or deep underground.
caveCheekLootChance = 0.5
# Chance (0.0 to 1.0) to find Cucumber, Green Bean, or Sunflower seeds in general loot chests.
seedLootChance = 0.0
# Chance (0.0 to 1.0) to find Acorn, Iron, or Gold hamster armor in standard Dungeons, Temples, Mineshafts, etc.
standardArmorLootChance = 0.0
# Chance (0.0 to 1.0) to find Diamond hamster armor in high-level chests (End City, Nether Fortress).
highTierArmorLootChance = 0.0
# Vanilla horse armor doesn't spawn in Netherite, but maybe you think that's stupid. Enable this to allow Netherite Hamster Armor to appear in chests.
enableNetheriteArmorLoot = false
# Chance (0.0 to 1.0) to find Netherite Hamster Armor in high-level chests. Only applies if the toggle above is ON. Don't be too liberal with it. Or do. See if I care.
netheriteArmorLootChance = 0.1
# Chance (0.0 to 1.0) to find Iron and Gold upgrade templates in High-Tier chests (Bastions, Fortresses, etc).
basicSmithingTemplateLootChance = 0.1
# Chance (0.0 to 1.0) to find Diamond and Netherite upgrade templates in Legendary chests (Ancient Cities, Ominous Vaults, etc).
advancedSmithingTemplateLootChance = 0.05
# Chance (0.0 to 1.0) to find accessories in rare chests. Default is low.
accessoryLootChance = 0.05
# Chance (0.0 to 1.0) for an Oak Leaf block to drop an Acorn when broken. Default is low, similar to Apples.
oakLeavesAcornDropChance = 0.005
# Higher = slower, lower = faster. Makes perfect sense.
wildBushRegrowthModifier = 1.0
# Higher = slower, lower = faster. Photosynthesis is hard, okay?
sunflowerRegrowthModifier = 1.0
# A list of biome tags where these custom Sunflowers can replace vanilla ones. My custom union tag 'adorablehamsterpets:is_plains' points to 'c:is_plains', which provides wide compatibility with modded biomes.
sunflowerBiomeTags = [
    "minecraft:is_overworld"
]
# Specific biome IDs where these sunflowers can replace the vanilla ones. Format: 'mod_id:biome_name'. They’re picky.
sunflowerBiomes = []
# Enables the 'CasualAnimalEnjoyer' Protocol. A small chance for a random nearby sunflower to become a bioluminescent beacon at night— a reference to the Kikoriki cartoon, 'It Can't Be True' episode, around the 3:22 mark. Added upon request as a thank-you to CasualAnimalEnjoyer for their massive help with mod compatibility.
enableGlowingSunflowers = true
# 1 in X random ticks (20 ticks per second). Lower = more likely. Higher = more rare. Note: This only runs at night.
glowingSunflowerChance = 1000
# 1 in X chunks. Lower numbers means cucumbers take over the planet.
wildCucumberBushRarity = 24
# Biome tags where cucumbers feel at home. Format: 'mod_id:tag_name', for example: 'minecraft:is_jungle'.
cucumberBushTags = []
# Convention tags for maximum mod-pack harmony. Format: 'namespace:tag_name', for example: 'adorablehamsterpets:is_temperate', which points to the 'c:is_temperate' convention tag.
cucumberBushConventionTags = []
# Specific biome IDs where cucumbers can sprout. Format: 'mod_id:biome_name', for example: 'minecraft:savanna'.
cucumberBushBiomes = [
    "biomesoplenty:pasture",
    "minecraft:sunflower_plains",
    "biomesoplenty:woodland",
    "biomesoplenty:old_growth_woodland"
]
# Biomes where cucumbers are absolutely NOT allowed. Overrides everything else. Format: 'mod_id:biome_name', for example: 'minecraft:ocean'.
cucumberBushExclusions = []
# 1 in X chunks. Lower = beanpocalypse. For those of you in the back, it means they'll spam everywhere.
wildGreenBeanBushRarity = 24
# Biome tags for bean growth. Empty by default—choose wisely. Format: 'mod_id:tag_name', for example: 'minecraft:is_jungle'.
greenBeanBushTags = []
# Convention tags for mod-friendly bean spam. Format: 'namespace:tag_name', for example: 'adorablehamsterpets:is_wet', which points to the 'c:is_wet' convention tag.
greenBeanBushConventionTags = []
# Specific biomes where beans sprout like gossip in chat. Format: 'mod_id:biome_name', for example: 'minecraft:swamp'.
greenBeanBushBiomes = [
    "biomesoplenty:grassland",
    "biomesoplenty:pasture",
    "minecraft:lush_caves",
    "biomesoplenty:marsh"
]
# Absolutely no beans here, thank you very much. Overrides all other settings. Format: 'mod_id:biome_name', for example: 'minecraft:beach'.
greenBeanBushExclusions = []